### ISSUE TITLE
About Loss_FA

### ISSUE THREAD

**Issue by chenzean** [honeygupta/UGSR#1]
This is a great work, but I don't understand some of the content in the paper.
1. Are there two models involved in the paper?
2. I don’t quite understand the Loss_FA part.
Can you explain it in more detail?

**Comment by lDairyl** [comment]
自动回复：     您好，我是卢大瑞。我已经收到您的来信，谢谢。但是请注意，并不表明我已经阅读了您的邮件。祝好卢大瑞

**Comment by lDairyl** [comment]
自动回复：     您好，我是卢大瑞。我已经收到您的来信，谢谢。但是请注意，并不表明我已经阅读了您的邮件。祝好卢大瑞
